[2025-03-20T13:10:09.471+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [queued]>
[2025-03-20T13:10:09.483+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [queued]>
[2025-03-20T13:10:09.484+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-20T13:10:09.484+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-03-20T13:10:09.485+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-20T13:10:09.513+0000] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_alert> on 2025-03-20 13:00:00+00:00
[2025-03-20T13:10:09.519+0000] {standard_task_runner.py:55} INFO - Started process 774 to run task
[2025-03-20T13:10:09.523+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tech_sentiment_pipeline', 'send_alert', 'scheduled__2025-03-20T13:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/sentiment_ETL_pipeline.py', '--cfg-path', '/tmp/tmpadxb25i6']
[2025-03-20T13:10:09.525+0000] {standard_task_runner.py:83} INFO - Job 28: Subtask send_alert
[2025-03-20T13:10:09.609+0000] {task_command.py:389} INFO - Running <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [running]> on host 9f648da9db19
[2025-03-20T13:10:09.715+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tech_sentiment_pipeline
AIRFLOW_CTX_TASK_ID=send_alert
AIRFLOW_CTX_EXECUTION_DATE=2025-03-20T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-20T13:00:00+00:00
[2025-03-20T13:10:09.728+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-20T13:10:09.728+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-20T13:10:09.732+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/email.py", line 87, in execute
    custom_headers=self.custom_headers,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 72, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 120, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 231, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 265, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
[2025-03-20T13:10:09.743+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=tech_sentiment_pipeline, task_id=send_alert, execution_date=20250320T130000, start_date=20250320T131009, end_date=20250320T131009
[2025-03-20T13:10:09.765+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 28 for task send_alert ([Errno 101] Network is unreachable; 774)
[2025-03-20T13:10:09.774+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-03-20T13:10:09.792+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-20T13:16:03.177+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [queued]>
[2025-03-20T13:16:03.189+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [queued]>
[2025-03-20T13:16:03.189+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-03-20T13:16:03.190+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-03-20T13:16:03.190+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-03-20T13:16:03.212+0000] {taskinstance.py:1304} INFO - Executing <Task(EmailOperator): send_alert> on 2025-03-20 13:00:00+00:00
[2025-03-20T13:16:03.220+0000] {standard_task_runner.py:55} INFO - Started process 218 to run task
[2025-03-20T13:16:03.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tech_sentiment_pipeline', 'send_alert', 'scheduled__2025-03-20T13:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/sentiment_ETL_pipeline.py', '--cfg-path', '/tmp/tmpzxg0ncqx']
[2025-03-20T13:16:03.224+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask send_alert
[2025-03-20T13:16:03.300+0000] {task_command.py:389} INFO - Running <TaskInstance: tech_sentiment_pipeline.send_alert scheduled__2025-03-20T13:00:00+00:00 [running]> on host 228fbd75e4c1
[2025-03-20T13:16:03.398+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tech_sentiment_pipeline
AIRFLOW_CTX_TASK_ID=send_alert
AIRFLOW_CTX_EXECUTION_DATE=2025-03-20T13:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-20T13:00:00+00:00
[2025-03-20T13:16:03.412+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:120 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-03-20T13:16:03.413+0000] {email.py:229} INFO - Email alerting: attempt 1
[2025-03-20T13:16:04.755+0000] {email.py:241} INFO - Sent an alert email to ['challamallasunilreddy00553@gmail.com']
[2025-03-20T13:16:06.196+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=tech_sentiment_pipeline, task_id=send_alert, execution_date=20250320T130000, start_date=20250320T131603, end_date=20250320T131606
[2025-03-20T13:16:06.241+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-03-20T13:16:06.263+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
